const QUESTION_BANK = [
  {id:'q_001',en:'What small thing from today is still sitting beside you?',zh:'今天有哪些微不足道的小事，至今仍伴在你身边？',category:['daily','self'],depth:1,tone:['quiet'],niche:false},
  {id:'q_002',en:'If today had a temperature, what would it be?',zh:'如果今天有温度，会是什么样的？',category:['daily','city'],depth:1,tone:['soft'],niche:false},
  {id:'q_003',en:'What did you do today without really noticing you did it?',zh:'今天有什么事是你不知不觉就做了的？',category:['daily','self'],depth:2,tone:['observant'],niche:false},
  {id:'q_004',en:'What would make today one percent easier?',zh:'有什么东西可以让今天轻松一点点，哪怕只有百分之一？',category:['daily','self'],depth:1,tone:['gentle'],niche:false},
  {id:'q_005',en:'What sentence would you put on a note and leave on your desk today?',zh:'如果今天要在桌上留一张纸条，你会写哪句话？',category:['daily','art'],depth:2,tone:['quiet'],niche:false},
  {id:'q_006',en:'Which part of you has been speaking very quietly lately?',zh:'你内心的哪一部分最近一直低声细语？',category:['self'],depth:3,tone:['introspective'],niche:false},
  {id:'q_007',en:'What are you pretending not to want?',zh:'有什么是你假装自己并不想要的？',category:['self','unknown'],depth:4,tone:['dark'],niche:false},
  {id:'q_008',en:'What kind of person do you become when no one is asking anything from you?',zh:'当没有人向你索取什么时，你会变成什么样？',category:['self'],depth:4,tone:['quiet'],niche:false},
  {id:'q_009',en:'What did you almost say today?',zh:'今天有没有一句话，差一点就说出口了？',category:['self','relationship'],depth:3,tone:['withheld'],niche:false},
  {id:'q_010',en:'What would you like to be forgiven for, even if no one blamed you?',zh:'即使没人怪你，你还是希望别人原谅你什么？',category:['self','unknown'],depth:5,tone:['tender'],niche:false},
  {id:'q_011',en:'Which older version of you came back today?',zh:'今天，哪个过去的你又回来了？',category:['memory','self'],depth:3,tone:['nostalgic'],niche:false},
  {id:'q_012',en:'What place do you miss without knowing whether you were happy there?',zh:'有没有一个地方，你很想念，却也说不清当时到底快不快乐？',category:['memory','city'],depth:4,tone:['nostalgic'],niche:false},
  {id:'q_013',en:'What object has kept too much of your past?',zh:'有没有什么物件，替你留住了太多过去？',category:['memory'],depth:3,tone:['object'],niche:false},
  {id:'q_014',en:'Which memory becomes softer every time you retell it?',zh:'哪段记忆，每讲一次，就变得更柔软一点？',category:['memory','relationship'],depth:3,tone:['soft'],niche:false},
  {id:'q_015',en:'What did you once think would never change?',zh:'你曾经以为什么永远不会变？',category:['memory','future'],depth:4,tone:['wistful'],niche:false},
  {id:'q_016',en:'Who has been living in the corner of your mind without paying rent?',zh:'最近谁一直在你的脑海里占着一席之地却不付房租？',category:['relationship','daily'],depth:2,tone:['light'],niche:false},
  {id:'q_017',en:'What kind of closeness scares you a little?',zh:'哪一种亲近会让你有一点害怕？',category:['relationship','unknown'],depth:4,tone:['vulnerable'],niche:false},
  {id:'q_018',en:'What do you wish someone could understand without you translating yourself?',zh:'有什么事，你希望别人不用你解释，也能懂？',category:['relationship','connection'],depth:4,tone:['longing'],niche:false},
  {id:'q_019',en:'Which person feels far away even when they are not?',zh:'有没有一个人，明明没有那么远，却总像隔着很远？',category:['relationship','connection'],depth:4,tone:['distant'],niche:false},
  {id:'q_020',en:'What small kindness stayed longer than it was supposed to?',zh:'有没有一点很小的善意，在你心里停留了很久？',category:['relationship','memory'],depth:2,tone:['warm'],niche:false},
  {id:'q_021',en:'Which song, scene, or sentence has been following you lately?',zh:'最近有没有一首歌、一个画面、或一句话一直跟着你？',category:['art','memory'],depth:2,tone:['nostalgic'],niche:false},
  {id:'q_022',en:'If this week were a film still, what would be in the frame?',zh:'如果这一周是一帧电影画面，画面里会有什么？',category:['art','city'],depth:2,tone:['visual'],niche:false},
  {id:'q_023',en:'What line would you underline today if no one saw the book?',zh:'如果这本书不会被任何人看见，今天你会划下哪一句？',category:['art','self'],depth:2,tone:['quiet'],niche:false},
  {id:'q_024',en:'What image understands you better than a person did this week?',zh:'这一周，有没有哪个画面比人还要更能懂你？',category:['art','relationship'],depth:3,tone:['visual'],niche:false},
  {id:'q_025',en:'What would you photograph today if it did not need to be beautiful?',zh:'如果今天拍的照片不需要拍得漂亮，你会拍什么？',category:['art','city'],depth:1,tone:['observant'],niche:false},
  {id:'q_026',en:'What did the street look like when you were not really there?',zh:'当你不在那里的时候，那条街是什么样子的？',category:['city','self'],depth:3,tone:['dissociated'],niche:false},
  {id:'q_027',en:'Which room has seen a version of you that no one else has?',zh:'“哪间房间曾见证过别人从未见过的你？”？',category:['city','memory'],depth:4,tone:['private'],niche:false},
  {id:'q_028',en:'What weather would fit your inside today?',zh:'今天你心里的天气是什么样的？',category:['city','daily'],depth:1,tone:['simple'],niche:false},
  {id:'q_029',en:'Where would you go today if the city promised not to ask why?',zh:'如果这座城市保证不追问原因，今天你会去哪里？',category:['city','unknown'],depth:3,tone:['wandering'],niche:false},
  {id:'q_030',en:'What does your window know about you?',zh:'你的窗户知道你什么？',category:['city','strange'],depth:2,tone:['dreamlike'],niche:false},
  {id:'q_031',en:'What door are you afraid to open because you do not know what waits behind it?',zh:'有没有一扇门，因为不知道后面是什么，所以你一直不敢打开？',category:['unknown'],depth:5,tone:['dark'],niche:false},
  {id:'q_032',en:'What part of the dark feels empty, and what part might be listening?',zh:'黑暗里的哪一部分像是空的，哪一部分又像在听你说话？',category:['unknown','connection'],depth:5,tone:['existential'],niche:false},
  {id:'q_033',en:'What do you do when something outside says hurry, but your body says hide?',zh:'当外面有什么在催促你，而身体只想躲起来的时候，你会怎么办？',category:['unknown','self'],depth:4,tone:['honest'],niche:false},
  {id:'q_034',en:'What unknown thing has become larger because you have not looked at it?',zh:'有没有什么事，因为你一直不敢直视它，反而变得越来越大越严重？',category:['unknown'],depth:4,tone:['shadow'],niche:false},
  {id:'q_035',en:'If the dark were not a threat but a room, what would be inside?',zh:'如果黑暗不是威胁，而是一间房间，里面会有什么？',category:['unknown','strange'],depth:4,tone:['dreamlike'],niche:false},
  {id:'q_036',en:'What fear is trying to protect you, even if it is doing it badly?',zh:'有没有一种恐惧，其实是在保护你，即使方式很笨？',category:['unknown','self'],depth:5,tone:['gentle'],niche:false},
  {id:'q_037',en:'What tiny thought would you send to someone far away today?',zh:'今天你会把哪一个很小的念头寄给远方的人？',category:['connection'],depth:2,tone:['bottle'],niche:false},
  {id:'q_038',en:'What would make you feel that a stranger, somewhere, was also awake?',zh:'什么会让你觉得，在很远的地方，也有一个陌生人醒着？',category:['connection','unknown'],depth:3,tone:['faraway'],niche:false},
  {id:'q_039',en:'What kind of answer would make you feel less alone, even by one percent?',zh:'什么样的回答能让你感觉孤独感减轻，哪怕只有百分之一？',category:['connection','relationship'],depth:4,tone:['longing'],niche:false},
  {id:'q_040',en:'If someone in another city found this light, what do you hope they would understand?',zh:'如果另一个城市的人捡到这盏光，你希望TA明白什么？',category:['connection','city'],depth:4,tone:['bottle'],niche:false},
  {id:'q_041',en:'What feeling do you suspect belongs to more people than just you?',zh:'有没有一种感受，你觉得也许不只你一个人有？',category:['connection','self'],depth:3,tone:['shared'],niche:false},
  {id:'q_042',en:'If your shadow answered for you today, what would it say?',zh:'如果今天你的影子替你回答，它会说什么？',category:['strange','self'],depth:2,tone:['dreamlike'],niche:false},
  {id:'q_043',en:'What has been knocking from inside a dream?',zh:'最近有什么东西像是从梦里面敲门？',category:['strange','unknown'],depth:3,tone:['surreal'],niche:false},
  {id:'q_044',en:'If today had a secret animal, what would it be doing?',zh:'如果今天有一只秘密动物，它正在做什么？',category:['strange','daily'],depth:1,tone:['weird'],niche:false},
  {id:'q_045',en:'Which impossible place feels strangely familiar?',zh:'哪个不可能存在的地方，却让你觉得很熟悉？',category:['strange','memory'],depth:3,tone:['dreamlike'],niche:false},
  {id:'q_046',en:'What would the sea ask you if it forgot how to be gentle?',zh:'如果海忘了怎么温柔，它会问你什么？',category:['strange','unknown'],depth:4,tone:['sea'],niche:false},
  {id:'q_047',en:'What future are you avoiding because naming it would make it real?',zh:'你在回避哪一种未来，因为一旦说出口它就好像成真了？',category:['future','unknown'],depth:5,tone:['uncertain'],niche:false},
  {id:'q_048',en:'What do you hope will still be with you a year from now?',zh:'一年以后，你希望什么还留在你身边？',category:['future','connection'],depth:3,tone:['hopeful'],niche:false},
  {id:'q_049',en:'What small future could you bear to imagine today?',zh:'今天，你能想象的最小的未来是什么？',category:['future','daily'],depth:2,tone:['gentle'],niche:false},
  {id:'q_050',en:'Which version of tomorrow feels least impossible?',zh:'哪一种明天，听起来最不遥远？',category:['future','self'],depth:2,tone:['soft'],niche:false},
  {id:'q_051',en:'What did you carry today that did not belong to you?',zh:'今天你替谁、或替什么，背负了一点不属于你的东西？',category:['self','relationship'],depth:4,tone:['heavy'],niche:false},
  {id:'q_052',en:'What has been asking for your attention in a very indirect way?',zh:'有什么事一直绕着弯想让你注意到它？',category:['self','unknown'],depth:3,tone:['unclear'],niche:false},
  {id:'q_053',en:'What would you tell the person who is afraid of the hallway?',zh:'你会对那个害怕走进走廊的人说什么？',category:['unknown','connection'],depth:4,tone:['tender'],niche:false},
  {id:'q_054',en:'What kind of light would not hurt your eyes today?',zh:'今天哪一种光不会刺痛你的眼睛？',category:['daily','unknown'],depth:2,tone:['soft'],niche:false},
  {id:'q_055',en:'What part of you still believes in signs?',zh:'你身上的哪一部分，仍然相信某种征兆？',category:['strange','self'],depth:3,tone:['mystic'],niche:false},
  {id:'q_056',en:'What did you notice today that no one asked you to notice?',zh:'今天，有什么是你注意到却没人让你注意到的？',category:['daily','city'],depth:1,tone:['observant'],niche:false},
  {id:'q_057',en:'What would you put into a bottle if you did not need to be understood completely?',zh:'如果不需要被完全理解，你会把什么放进漂流瓶？',category:['connection','art'],depth:3,tone:['bottle'],niche:false},
  {id:'q_058',en:'Which silence felt crowded?',zh:'哪一种沉默，反而显得很拥挤？',category:['relationship','unknown'],depth:4,tone:['quiet'],niche:false},
  {id:'q_059',en:'What is one thing you are not ready to brighten yet?',zh:'有什么事，是你现在还不准备照亮的？',category:['unknown'],depth:5,tone:['dark'],niche:false},
  {id:'q_060',en:'Where did your mind go when it had nowhere to go?',zh:'当你的脑子无处可去的时候，它去了哪里？',category:['self','strange'],depth:3,tone:['wandering'],niche:false}
];

const BOTTLE_MSGS = [
  {text:"I watched the rain for two hours and thought of nothing. It was the best two hours I've had in months.",src:'from Shanghai'},
  {text:"I still haven't called my father back. It's been three months.",src:'from Oslo'},
  {text:"I laughed so hard last night that I cried. I can't remember the joke anymore.",src:'from Buenos Aires'},
  {text:"I think I'm falling out of love and I don't know how to be sad about it.",src:'from Tokyo'},
  {text:"Today I bought flowers for myself. It felt strange and exactly right.",src:'from Lisbon'},
  {text:"I've been drawing the same face for years. I still don't know whose it is.",src:'from Montréal'},
  {text:"I said I was fine. I was not fine. Neither was she. We both knew. We kept going.",src:'from Seoul'},
  {text:"I found a note I wrote to myself at seventeen. I wasn't wrong about everything.",src:'from Berlin'},
  {text:"Some mornings I wake up feeling like a version of myself from five years ago.",src:'from Cape Town'},
  {text:"I keep a list of things I want to say to people who are gone. It gets longer every year.",src:'from Kyoto'},
  {text:"I finished a book today and held it for a long time before putting it down.",src:'from Dublin'},
  {text:"I walked in a direction I didn't know for an hour. I found nothing. It was enough.",src:'from Istanbul'},
];

const CATEGORY_LABELS = {
  en:{daily:'daily life',self:'self',memory:'memory',relationship:'someone',strange:'strange',future:'future',unknown:'the unknown',connection:'connection'},
  zh:{daily:'日常',self:'自己',memory:'记忆',relationship:'关系',strange:'奇怪',future:'未来',unknown:'未知',connection:'连接'}
};

// ── STORAGE ───────────────────────────────────────────────────────────────────
